Entity/Issue.php
<?php

namespace Valouleloup\IssueBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;

class Issue
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $label;

    /**
     * @var string
     */
    private $body;

    /**
     * @var Collection
     */
    private $posts;

    /**
     * @var Collection
     */
    private $tags;

    /**
     * @var integer
     */
    private $state;

    /**
     * @var UserInterface
     */
    private $author;

    /**
     * @var Theme
     */
    private $theme;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * Issue constructor.
     */
    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
    }

    /**
     * @return Collection
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * @param Post $post
     */
    public function setPosts($post)
    {
        $this->posts->add($post);

        $post->setIssue($this);
    }

    /**
     * @return Collection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param Tag $tag
     */
    public function setTags($tag)
    {
        $this->tags->add($tag);

        $tag->setIssues($this);
    }

    /**
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param int $state
     */
    public function setState($state)
    {
        $this->state = $state;
    }

    /**
     * @return UserInterface
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param UserInterface $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return int
     */
    public function getNbPosts()
    {
        return count($this->posts);
    }

    /**
     * @return Theme
     */
    public function getTheme()
    {
        return $this->theme;
    }

    /**
     * @param Theme $theme
     */
    public function setTheme($theme)
    {
        $this->theme = $theme;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param string $body
     */
    public function setBody($body)
    {
        $this->body = $body;
    }

}

Form/IssueType.php
<?php

namespace Valouleloup\IssueBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Valouleloup\IssueBundle\Entity\Issue;
use Valouleloup\IssueBundle\Entity\Tag;
use Valouleloup\IssueBundle\Entity\Theme;

class IssueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', TextType::class)
            ->add('body', TextareaType::class)
            ->add('theme', EntityType::class, [
                'class' => Theme::class,
                'choice_label' => 'label'
            ])
            ->add('tags', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => 'label',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Issue::class,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'form_issue';
    }
}

Controller/IssueController.php
<?php

namespace Valouleloup\IssueBundle\Controller;

use League\CommonMark\CommonMarkConverter;
use League\CommonMark\Converter;
use League\CommonMark\DocParser;
use League\CommonMark\Environment;
use League\CommonMark\HtmlRenderer;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Valouleloup\IssueBundle\Entity\Issue;
use Valouleloup\IssueBundle\Entity\Post;
use Valouleloup\IssueBundle\Entity\Tag;
use Valouleloup\IssueBundle\Entity\Theme;
use Valouleloup\IssueBundle\Form\ElasticType;
use Valouleloup\IssueBundle\Form\IssueType;
use Valouleloup\IssueBundle\Form\PostType;
use Webuni\CommonMark\TableExtension\TableExtension;

class IssueController extends Controller
{
    public function showAction(Issue $issue)
    {
        $post = new Post();

        $form = $this->createForm(
            PostType::class,
            $post,
            [
                'action' => $this->generateUrl('show_issue_new_post', ['id' => $issue->getId()]),
                'method' => 'POST',
            ]
        );

        $environment = Environment::createCommonMarkEnvironment();
        $environment->addExtension(new TableExtension());

        $converter = new Converter(new DocParser($environment), new HtmlRenderer($environment));

        foreach ($issue->getPosts() as $post) {
            $post->setBody($converter->convertToHtml($post->getBody()));
        }

        $issue->setBody($converter->convertToHtml($issue->getBody()));

        return $this->render('@ValouleloupIssue/Issue/show.html.twig', [
            'issue' => $issue,
            'form' => $form->createView(),
        ]);
    }

    public function showNewPostAction(Request $request, Issue $issue)
    {
        $post = new Post();
        $post->setIssue($issue);
        $post->setAuthor($this->getUser());

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $issue->setUpdatedAt(new \DateTime('now'));

            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();

            $this->get('val_issue.component.elastic.post.manager')->indexPost($post);

            return $this->redirectToRoute('show_issue', ['id' => $issue->getId()]);
        }

        return $this->render('@ValouleloupIssue/Issue/show.html.twig', [
            'issue' => $issue,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return Response
     */
    public function listAction()
    {
        $repo = $this->getDoctrine()->getRepository('ValouleloupIssueBundle:Issue');
        $issues = $repo->findAllMostRecent();

        return $this->renderList($issues);
    }

    /**
     * @param Tag $tag
     *
     * @return Response
     */
    public function listTagAction(Tag $tag)
    {
        $repo = $this->getDoctrine()->getRepository('ValouleloupIssueBundle:Issue');
        $issues = $repo->findByTag($tag);

        return $this->renderList($issues);
    }

    /**
     * @param Theme $theme
     *
     * @return Response
     */
    public function listThemeAction(Theme $theme)
    {
        $repo = $this->getDoctrine()->getRepository('ValouleloupIssueBundle:Issue');
        $issues = $repo->findByTheme($theme);

        return $this->renderList($issues);
    }

    /**
     * @param $terms
     *
     * @return Response
     */
    public function listElasticAction($terms)
    {
        $repo = $this->getDoctrine()->getRepository('ValouleloupIssueBundle:Issue');

        $postIds = $this->get('val_issue.component.elastic.post.manager')->getPosts($terms);

        $issues = $repo->findByListId($postIds);

        return $this->renderList($issues);
    }

    /**
     * @return Response
     */
    public function listSearchAction(Request $request)
    {
        $form = $this->createForm(ElasticType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $search = $form->get('search')->getData();

            return $this->redirectToRoute('list_issue_elastic', ['terms' => $search]);
        }

        return $this->redirectToRoute('list_issue');
    }

    /**
     * @param $issues
     *
     * @return Response
     */
    private function renderList($issues)
    {
        $form = $this->createForm(ElasticType::class, null, [
            'action' => $this->generateUrl('list_issue_search'),
            'method' => 'POST',
        ]);

        $paginator = $this->get('val_issue.component.pagination.paginator');
        $issues    = $paginator->paginate($issues, 5);

        return $this->render('@ValouleloupIssue/Issue/list.html.twig', [
            'issues' => $issues,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return Response
     */
    public function newAction()
    {
        $issue = new Issue();

        $form = $this->createForm(
            IssueType::class,
            $issue,
            [
                'action' => $this->generateUrl('create_issue'),
                'method' => 'POST',
            ]
        );

        return $this->render('@ValouleloupIssue/Issue/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function createAction(Request $request)
    {
        $issue = new Issue();
        $issue->setAuthor($this->getUser());

        $form = $this->createForm(IssueType::class, $issue);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($issue);
            $em->flush();

            $this->get('val_issue.component.elastic.post.manager')->indexIssue($issue);

            $this->addFlash('success', 'flash.issue.create');

            return $this->redirectToRoute('list_issue');
        }

        return $this->render('@ValouleloupIssue/Issue/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

Resources/views/Issue/add.html.twig
{% extends '@ValouleloupIssue/Issue/base_issue.html.twig' %}

{% block body %}
    <div class="row">
        <div class="panel panel-default send-issue" id="send-issue">

            <div class="panel-heading">New Issue</div>
            <div class="panel-body">
                <div class="form">
                    {{ form_start(form) }}
                    {{ form_row(form.label) }}
                    {{ form_row(form.body, {'attr': {'cols': '120', 'rows': '10'}}) }}
                    {{ form_row(form.theme) }}
                    {{ form_row(form.tags) }}
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-success btn-submit pull-right'}, 'label' : 'Add Issue'}) }}
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

Resources/views/Issue/base_issue.html.twig
{% extends '@ValouleloupIssue/base.html.twig' %}

{% block current_top_navigation %}
    <h4><a>Home</a> / <a>Issues</a></h4>
{% endblock %}

{% block body_nav_issues %}
    <li class="active">
        <a href="{{ path('list_issue') }}">Issues {% block issue_list_badge %}{% endblock %}</a>
    </li>
{% endblock %}

Resources/views/Issue/list.html.twig
{% extends '@ValouleloupIssue/Issue/base_issue.html.twig' %}

{% block issue_list_badge %}
    <span class="badge">{{ issues|length }}</span>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-6 col-no-padding">
            {{ form_start(form) }}
            {{ form_end(form) }}
            <button type="submit" class="elastic-submit">OK</button>
        </div>
        <div class="col-sm-6 col-no-padding">
            <a class="btn btn-success pull-right" href="{{ path('add_issue') }}">Add Issue</a>
        </div>
    </div>

    <div class="row">
        <div class="panel panel-default list-elements">

            <div class="panel-heading"> List issues </div>
            <div class="panel-body">
                {% for issue in issues %}
                    <div class="col-sm-12 single-element">
                        <div class="col-sm-10 title col-no-padding">
                            <div class="issue-state">
                                {% if issue.state == 0 %}
                                <span class="issue-state-open glyphicon glyphicon-play-circle"></span>
                                {% elseif issue.state == 1 %}
                                <span class="issue-state-closed glyphicon glyphicon-download"></span>
                                {% endif %}
                            </div>
                            <div class="issue-title">
                                <a href="{{ path('show_issue', {'id': issue.id}) }}">{{ issue.label }}</a> - {{ issue.author.username }}
                                {% for tag in issue.tags %}
                                    <a href="{{ path('list_issue_tag', {'id': tag.id}) }}" class="label label-warning" style="background-color:#{{ tag.color }};">{{ tag.label }}</a>
                                {% endfor %}
                                <p>#{{ issue.id }} created at {{ issue.createdAt|date('d/m/Y H:i:s') }}</p>
                            </div>
                        </div>
                        <div class="col-sm-2 infos info-comments text-right">
                            <a href="{{ path('show_issue', {'id': issue.id}) }}"><span class="glyphicon glyphicon-comment"></span> {{ issue.nbPosts }} comments</a>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

{% block paginate %}
    {{ paginate.navigation(issues) }}
{% endblock %}

Resources/views/Issue/show.html.twig
{% extends '@ValouleloupIssue/Issue/base_issue.html.twig' %}

{% block current_top_navigation %}
    <h4><a>{{ issue.theme.label }}</a> / <a><b>{{ issue.label }}</b></a></h4>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="header-issue col-sm-12">
            <h2>{{ issue.label }}</h2> <span class="label label-success">Open</span>
            {% for tag in issue.tags %}
                <span class="label label-warning" style="background-color:#{{ tag.color }};">{{ tag.label }}</span>
            {% endfor %}
        </div>

        <div class="single-post col-sm-12 col-no-padding">
            <div class="col-sm-1 post-left">
                <img src="{{ asset('ident02.png') }}">
            </div>

            <div class="panel panel-default col-sm-11 list-posts">

                <div class="panel-heading">
                    {{ issue.author.username }} commented at {{ issue.createdAt|date('d/m/Y H:i:s') }}
                </div>
                <div class="panel-body">
                    <p>{{ issue.body | raw }}</p>
                </div>

            </div>
        </div>
    </div>

    <hr>

    <div class="row">
    {% for post in issue.posts %}
        <div class="single-post col-sm-12 col-no-padding">
            <div class="col-sm-1 post-left">
                <img src="{{ asset('ident02.png') }}">
            </div>

            <div class="panel panel-default col-sm-11 col-no-padding">

                <div class="panel-heading">
                    {{ post.author.username }} commented at {{ post.createdAt|date('d/m/Y H:i:s') }}
                    {% if post.author.id == app.user.id %}
                        <a href="{{ path('edit_post', {'id': post.id}) }}" class="pull-right">Edit</a>
                    {% endif %}
                </div>
                <div class="panel-body">
                    <p>{{ post.body | raw }}</p>
                </div>

            </div>
        </div>
    {% endfor %}
    </div>

    <hr>

    <div class="row">
        <div class="panel panel-default send-post" id="send-post">

            <div class="panel-heading">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#">Write</a></li>
                    <li><a href="#">Preview</a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="form">
                    {{ form_start(form) }}
                    {{ form_widget(form.body, {'attr': {'class': 'col-sm-12'}}) }}
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-success btn-submit pull-right'}, 'label' : 'Comment'}) }}
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </div>
{% endblock %}